# This is the recipe to create a noarch conda package for Flexx

package:
  name: flexx
  version: "0.3.1"

source:
  fn: flexx-0.3.1.zip
  url: https://pypi.python.org/packages/source/f/flexx/flexx-0.3.1.zip
  md5: 58f7420e3dccee0b4b5aa70625e63161

build:
  script: python setup.py install
  noarch_python: True
  number: 1
  entry_points:
    - flexx = flexx.__main__:main

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - tornado

test:
  # Python imports
  imports:
    - flexx
    - flexx.app
    - flexx.pyscript
    - flexx.react
    - flexx.ui
    - flexx.webruntime

about:
  home: http://flexx.readthedocs.org
  license: BSD License
  summary: "Pure Python toolkit for creating GUI's using web technology."

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
